SphinxBase: include/mmio.h File Reference
include/mmio.h File Reference
Memory-mapped I/O wrappers for files.
#include <sphinxbase_export.h>
Typedefs
typedef struct mmio_file_s mmio_file_t
Abstract structure representing a memory-mapped file.
Functions
SPHINXBASE_EXPORT mmio_file_t * mmio_file_read (const char *filename)
Memory-map a file for reading.
SPHINXBASE_EXPORT void * mmio_file_ptr (mmio_file_t *mf)
Get a pointer to the memory mapped for a file.
SPHINXBASE_EXPORT void mmio_file_unmap (mmio_file_t *mf)
Unmap a file, releasing memory associated with it.
Detailed Description
Memory-mapped I/O wrappers for files.
Author:
David Huggins-Daines <dhuggins@cs.cmu.edu>
Definition in file mmio.h.
Function Documentation
SPHINXBASE_EXPORT mmio_file_t* mmio_file_read (const char * filename)
Memory-map a file for reading.
Returns:
a mmio_file_t * or NULL for failure.
Definition at line 204 of file mmio.c.
References ckd_calloc, E_ERROR, E_ERROR_SYSTEM, mmio_file_s::mapsize, mmio_file_read(), and mmio_file_s::ptr.
Referenced by logmath_read(), and mmio_file_read().